platform :ios, '13.0'

target 'esimkitapp' do
  use_frameworks!
  
  pod 'RNCryptor'
  pod 'Alamofire'
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'RxDataSources'
  pod 'Kingfisher'
  
  pod 'IBAnimatable'
  pod 'KeychainSwift'
  pod 'NVActivityIndicatorView'
  pod 'CryptoSwift'
  pod 'DateToolsSwift'
  pod 'PhoneNumberKit'
  pod 'SwiftyStoreKit'
  pod 'SwiftWebVC', :git => 'https://github.com/Up2dateSoftware/SwiftWebVC'
  pod 'SAConfettiView', :git => 'https://github.com/isayeter/SAConfettiView'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
    
    # fix xcode 15 DT_TOOLCHAIN_DIR - remove after fix oficially - https://github.com/CocoaPods/CocoaPods/issues/12065
    installer.aggregate_targets.each do |target|
        target.xcconfigs.each do |variant, xcconfig|
            xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
            IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
        end
    end
    
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
                xcconfig_path = config.base_configuration_reference.real_path
                IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
            end
        end
    end
end
